### ISSUE TITLE
install on ubuntu natty x64 fails

### ISSUE THREAD

**Issue by stefancocora** [jssjr/collectd-write_graphite#6]
Your C plugin is an amazing idea !
It has failed to install for me on ubuntu 11.04 aka natty x64 with the below error : 

work/collectd-4.10.1/libtool --mode=compile gcc -DHAVE_CONFIG_H -I src \
        -I work/collectd-4.10.1/src -Wall -Werror -DNDEBUG -O3 -MD -MP -c \
        -o build/write_graphite.lo src/write_graphite.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I src -I work/collectd-4.10.1/src -Wall -Werror -DNDEBUG -O3 -MD -MP -c src/write_graphite.c  -fPIC -DPIC -o build/.libs/write_graphite.o
src/write_graphite.c:82:5: error: expected specifier-qualifier-list before ‘cdtime_t’
src/write_graphite.c: In function ‘wg_reset_buffer’:
src/write_graphite.c:96:7: error: ‘struct wg_callback’ has no member named ‘send_buf_init_time’
cc1: warnings being treated as errors
src/write_graphite.c:96:5: error: implicit declaration of function ‘cdtime’
src/write_graphite.c: In function ‘wg_send_buffer’:
src/write_graphite.c:111:32: error: ‘struct wg_callback’ has no member named ‘send_lock’
src/write_graphite.c:118:34: error: ‘struct wg_callback’ has no member named ‘send_lock’
src/write_graphite.c: At top level:
src/write_graphite.c:125:38: error: expected ‘)’ before ‘timeout’
src/write_graphite.c: In function ‘wg_callback_free’:
src/write_graphite.c:211:5: error: implicit declaration of function ‘wg_flush_nolock’
src/write_graphite.c: At top level:
src/write_graphite.c:221:31: error: expected ‘)’ before ‘timeout’
src/write_graphite.c:434:9: error: expected declaration specifiers or ‘...’ before ‘cdtime_t’
src/write_graphite.c: In function ‘wg_send_message’:
src/write_graphite.c:444:13: error: implicit declaration of function ‘CDTIME_T_TO_DOUBLE’
src/write_graphite.c:452:28: error: ‘struct wg_callback’ has no member named ‘send_lock’
src/write_graphite.c:460:38: error: ‘struct wg_callback’ has no member named ‘send_lock’
src/write_graphite.c:470:38: error: ‘struct wg_callback’ has no member named ‘send_lock’
src/write_graphite.c:491:30: error: ‘struct wg_callback’ has no member named ‘send_lock’
src/write_graphite.c: In function ‘wg_write_messages’:
src/write_graphite.c:535:13: error: passing argument 3 of ‘wg_send_message’ makes pointer from integer without a cast
src/write_graphite.c:433:12: note: expected ‘struct wg_callback *’ but argument is of type ‘time_t’
src/write_graphite.c:535:13: error: too many arguments to function ‘wg_send_message’
src/write_graphite.c:433:12: note: declared here
src/write_graphite.c:566:9: error: passing argument 3 of ‘wg_send_message’ makes pointer from integer without a cast
src/write_graphite.c:433:12: note: expected ‘struct wg_callback *’ but argument is of type ‘time_t’
src/write_graphite.c:566:9: error: too many arguments to function ‘wg_send_message’
src/write_graphite.c:433:12: note: declared here
src/write_graphite.c: In function ‘wg_config_carbon’:
src/write_graphite.c:672:28: error: ‘struct wg_callback’ has no member named ‘send_lock’
src/write_graphite.c:719:46: error: ‘wg_flush’ undeclared (first use in this function)
src/write_graphite.c:719:46: note: each undeclared identifier is reported only once for each function it appears in
src/write_graphite.c: At top level:
src/write_graphite.c:99:12: error: ‘wg_send_buffer’ defined but not used

Any ideas why ?

**Comment by jssjr** [comment]
The current version of this plugin is not compatible with Collectd 4.x. The change to 5.0.0 created new types for timing variables instead of using the ISO time_t type. I expect this is to force 64bit variable for higher precision timing, but that is just a guess since I haven't read the relevant commit messages for this change.

Any chance you can take the plunge and upgrade to Collectd 5?
