### ISSUE TITLE
plugin locks up if it can't write data to socket

### ISSUE THREAD

**Issue by jimmyattime** [jssjr/collectd-write_graphite#8]
If the network connection or cache-cache gets restarted, the plugin goes into a blocking state. collectd then needs to be kill -KILL to shutdown. The work around is doing a pthread_mutex_trylock instead of pthread_mutex_lock if the write fails.

```
@@ -105,7 +107,7 @@
             status,
             strerror (errno));

-        pthread_mutex_lock (&cb->send_lock);
+        pthread_mutex_trylock (&cb->send_lock);

     DEBUG ("write_graphite plugin: closing socket and restting fd "
             "so reinit will occur");
```

**Comment by jssjr** [comment]
Thanks for reporting this issue. I will verify the fix and commit the changes shortly.

**Comment by jssjr** [comment]
Committed. Sorry for the delay.
